-- AlterTable
ALTER TABLE "Table" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 80,
ADD COLUMN     "posX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "posY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "shape" TEXT NOT NULL DEFAULT 'rectangle',
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 80;
